on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.2
        with:
          version: master
      - name: Run tests
        run: zig build test
        
  build:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.2
        with:
          version: master
      - name: Build in Debug mode
        run: zig build
      - name: Upload macOS build
        uses: actions/upload-artifact@v1.0.0
        with:
          name: zig-synth-macos
          path: zig-cache/bin/zig-synth
      - name: Upload browser build
        uses: actions/upload-artifact@v1.0.0
        with:
          name: zig-synth-browser.html
          path: zig-cache/bin/zig-synth.html
        
  publish-html:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.2
        with:
          version: master
      - name: Build
        run: "zig build -Drelease-fast && mkdir public && cp zig-cache/bin/zig-synth.html public/index.html"
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
          allow_empty_commit: false
          committer_name: github-actions
          committer_email: ""
          commit_message: "Deploy browser build to GitHub Pages"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
